site_name: Text2Math
site_url: https://timmoth.github.io/Text2Math/
site_description: Simple mathematical expression evaluator.
site_author: Timmoth
repo_url: https://github.com/Timmoth/Text2Math/
edit_uri: edit/main/docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - csharp
nav:
  - Overview âœ…: index.md
  - Internals âœ…: internals.md
  - Releases ğŸ“’: releases.md
  - Support ğŸ›Ÿ: support.md
  - Contributing ğŸ™: contributing.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
